### ISSUE TITLE
Does not work on SCSM 2019

### ISSUE THREAD

**Issue by SIDFVAN** [microsoft/scsmservicerequest#1]
Problem with listpicker on SCSM 2019.

System.Windows.Markup.XamlParseException: 'Set connectionId threw an exception.' Line number '28' and line position '5'. ---> System.TypeLoadException: Could not load type 'Microsoft.EnterpriseManagement.UI.WpfControls.ListPicker' from assembly 'Microsoft.EnterpriseManagement.UI.SMControls, Version=7.0.5000.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Demo.ServiceRequest.ServiceRequest.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)

**Comment by SIDFVAN** [comment]
use all the latest dll's
